language: csharp
solution: src/ServiceConnect.sln
install:
  - nuget # lets get version number
  - nuget restore src/ServiceConnect.sln -Verbosity detailed
  - nuget update src/ServiceConnect.sln -Verbosity detailed
